version: '3.9'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: Pr1mary
      POSTGRES_PASSWORD: psqldb
      POSTGRES_DB: testjwt
    ports:
      - "5433:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
  web:
    container_name: Api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=testjwt
      - POSTGRES_USER=Pr1mary
      - POSTGRES_PASSWORD=psqldb